#spring:
#  profiles:
#    active: dev

dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.xavier.dong.springcloud.service
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
#    serialization: protobuf
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost