server:
  port: 84

spring:
  application:
    name: cloudalibaba-sentinel-consumer
  cloud:
    nacos:
      discovery:
        # Nacos 服务注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        # 配置 sentinel dashboard 地址
        dashboard: localhost:8080
        # 默认 8719 端口， 假如 被占用 会自动 从 8719 开始 依次 +1 扫描，直至找到 未被占用的端口
        port: 8719
# 激活 feign 对sentinel 的支持
feign:
  sentinel:
    enabled: true
